import { type VaultItem } from "@/lib/vaultModel";

export function getDemoItems(): VaultItem[] {
  const now = Date.now();

  return [
    {
      id: "demo_1",
      title: "Amazing Spider-Man",
      number: "#129",
      grade: "CGC 9.0",
      universe: "POP_CULTURE",
      category: "COMICS",
      categoryLabel: "Comics",
      subcategoryLabel: "Comic Book",
      purchasePrice: 120,
      currentValue: 450,
      estimatedValue: 450,
      priceSource: "eBay sold",
      priceConfidence: "high",
      priceUpdatedAt: now,
      notes: "First appearance of Punisher",
      createdAt: now - 1000000,
      isNew: false,
    },
    {
      id: "demo_2",
      title: "Charizard",
      subtitle: "Base Set",
      grade: "PSA 8",
      universe: "TCG",
      category: "CARDS",
      categoryLabel: "Trading Cards",
      purchasePrice: 300,
      currentValue: 900,
      estimatedValue: 900,
      priceSource: "recent comps",
      priceConfidence: "medium",
      priceUpdatedAt: now,
      createdAt: now - 900000,
      isNew: false,
    },
    {
      id: "demo_3",
      title: "Rolex Submariner",
      universe: "JEWELRY_APPAREL",
      category: "WATCHES",
      categoryLabel: "Watches",
      purchasePrice: 8000,
      currentValue: 10500,
      estimatedValue: 10500,
      priceSource: "dealer ask",
      priceConfidence: "medium",
      priceUpdatedAt: now,
      createdAt: now - 800000,
      isNew: false,
    },
    {
      id: "demo_4",
      title: "Michael Jordan Rookie",
      grade: "BGS 8.5",
      universe: "SPORTS",
      category: "CARDS",
      categoryLabel: "Sports Cards",
      purchasePrice: 2500,
      currentValue: 6000,
      estimatedValue: 6000,
      priceSource: "auction",
      priceConfidence: "high",
      priceUpdatedAt: now,
      createdAt: now - 700000,
      isNew: false,
    },
    {
      id: "demo_5",
      title: "Super Mario Bros",
      subtitle: "NES",
      universe: "GAMES",
      category: "VIDEO_GAMES",
      categoryLabel: "Games",
      purchasePrice: 50,
      currentValue: 200,
      estimatedValue: 200,
      priceSource: "pricecharting",
      priceConfidence: "low",
      priceUpdatedAt: now,
      createdAt: now - 600000,
      isNew: false,
    },
  ];
}