// Part 4 — Characters 18–22: Rumplestiltskin, Walton J Jr, Erik, Solomon King, Kai Sterling

import type { SeedCharacter } from "./seedCharacters";

function iid(slug: string, n: number) {
  return `seed_${slug}_item_${String(n).padStart(3, "0")}`;
}
function gid(slug: string, n: number) {
  return `seed_${slug}_gallery_${n}`;
}

// ═══════════════════════════════════════════════════════════════
// 18 — RUMPLESTILTSKIN
// ═══════════════════════════════════════════════════════════════
const rumple: SeedCharacter = {
  profileId: "00000000-0000-0000-0000-000000000018",
  displayName: "Rumplestiltskin",
  handle: "rumplestiltskin",
  avatarEmoji: "🧶",
  bio: "Dealer in the impossible. Spinner of gold. Every bargain has a price, and Rumplestiltskin always collects. His vault is full of enchanted objects, cursed artifacts, and items acquired through deals no sensible person would sign — but everyone does eventually.",
  primaryFocus: "Historical Artifacts",
  items: [
    { id: iid("rumple", 1), title: "Spinning Wheel — Gold Thread", subtitle: "Enchanted oak, c. fairy tale era", universe: "Historical Artifacts", category: "Curiosities", notes: "Spins straw into gold. Last used in a miller's daughter's chamber.", currentValue: 4800000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("rumple", 2), title: "Contract Scroll — First Born Child", subtitle: "Vellum, signed in blood", universe: "Books & Manuscripts", category: "Legal Documents", notes: "The original deal. First of thousands. All legally binding.", currentValue: 2200000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("rumple", 3), title: "Midas's Golden Touch Gauntlet", subtitle: "Gold-plated leather, cursed", universe: "Historical Artifacts", category: "Curiosities", notes: "Everything it touches turns to gold. Handle with extreme care.", currentValue: 9800000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("rumple", 4), title: "True Name Ledger", subtitle: "Bound in human skin, iron clasp", universe: "Books & Manuscripts", category: "Grimoires", notes: "Every name in here can be commanded. 3,000 entries.", currentValue: 5600000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("rumple", 5), title: "Cinderella's Glass Slipper", subtitle: "Silica crystal, fitted for one foot only", universe: "Historical Artifacts", category: "Curiosities", notes: "Acquired in exchange for a pumpkin carriage and driver.", currentValue: 1200000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("rumple", 6), title: "Sleeping Beauty's Spindle", subtitle: "Enchanted iron, drop spindle", universe: "Historical Artifacts", category: "Curiosities", notes: "One prick causes century-long sleep. Still active.", currentValue: 3400000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("rumple", 7), title: "Magic Mirror — Snow White's", subtitle: "Obsidian glass, gold frame", universe: "Historical Artifacts", category: "Curiosities", notes: "Knows who is fairest. Compulsively honest. Deeply unhappy.", currentValue: 2800000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("rumple", 8), title: "Jack's Magic Beans — Set of Five", subtitle: "Dried legumes, extraordinary properties", universe: "Historical Artifacts", category: "Curiosities", notes: "Each grows a beanstalk to a different giant's kingdom.", currentValue: 480000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("rumple", 9), title: "Pinocchio's Original Nose Chip", subtitle: "Pine wood, grows when lying", universe: "Historical Artifacts", category: "Curiosities", notes: "Shaving from Geppetto's workshop. Still reactive to dishonesty.", currentValue: 280000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("rumple", 10), title: "Poison Apple — Preserved", subtitle: "Enchanted fruit, Snow White variety", universe: "Historical Artifacts", category: "Curiosities", notes: "Half-eaten. The other half is still in Snow White's story.", currentValue: 1800000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("rumple", 11), title: "Lamp — Djinn Vessel", subtitle: "Brass oil lamp, Arabian origin", universe: "Historical Artifacts", category: "Curiosities", notes: "Three wishes remaining. Previous owner used two poorly.", currentValue: 8400000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("rumple", 12), title: "Beanstalk Giant's Ring", subtitle: "Iron, sized for a 40-foot being", universe: "Historical Artifacts", category: "Jewelry", notes: "Fee-fi-fo-fum. Acquired from Jack in a secondary deal.", currentValue: 380000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("rumple", 13), title: "Rumpelstiltskin's True Name Certificate", subtitle: "Issued by the Fairy Court, witnessed", universe: "Books & Manuscripts", category: "Legal Documents", notes: "If anyone reads this aloud, the deal is nullified. SEALED.", currentValue: 6200000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("rumple", 14), title: "Pied Piper's Flute", subtitle: "Bone pipe, enchanted melody", universe: "Music & Instruments", category: "Ancient Instruments", notes: "Leads rats — and children. Acquired after Hamelin dispute.", currentValue: 2200000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("rumple", 15), title: "Red Riding Hood's Cloak", subtitle: "Scarlet wool, wolf-repelling enchantment", universe: "Historical Artifacts", category: "Curiosities", notes: "Actually repels wolves. Grandmother had better wool.", currentValue: 280000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("rumple", 16), title: "Frog Prince Lily Pad Collection", subtitle: "Preserved enchanted amphibian habitat", universe: "Natural History", category: "Curiosities", notes: "Seventeen princes mid-transformation. Stored for leverage.", currentValue: 680000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("rumple", 17), title: "Hansel and Gretel's Trail of Breadcrumbs", subtitle: "Petrified carbohydrates, c. fairy tale era", universe: "Historical Artifacts", category: "Curiosities", notes: "Birds ate the real ones. These are from the witch's backup set.", currentValue: 45000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("rumple", 18), title: "Witch's Cauldron — Baba Yaga", subtitle: "Iron, self-stirring, Russian tradition", universe: "Historical Artifacts", category: "Curiosities", notes: "Baba Yaga traded it for three questions answered.", currentValue: 980000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("rumple", 19), title: "Cursed Gold Coins — Pieces of Eight", subtitle: "Aztec gold, Pirates of the Caribbean type", universe: "Coins & Currency", category: "Ancient Coins", notes: "Every coin must be returned or the curse holds. Still 23 missing.", currentValue: 1200000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("rumple", 20), title: "Twelve Dancing Princesses' Silver Shoes", subtitle: "Set of twelve pairs, worn through at sole", universe: "Historical Artifacts", category: "Curiosities", notes: "Worn out every night in the underground kingdom.", currentValue: 480000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("rumple", 21), title: "Seven League Boots", subtitle: "Leather, enchanted stride", universe: "Historical Artifacts", category: "Curiosities", notes: "Each step covers seven leagues. Very hard to park.", currentValue: 1400000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("rumple", 22), title: "Grimm Brothers Manuscript — Fairy Tales", subtitle: "Jacob and Wilhelm Grimm, 1812 first edition", universe: "Books & Manuscripts", category: "Rare Books", notes: "His stories are in here. He finds this amusing.", currentValue: 285000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("rumple", 23), title: "Enchanted Rose — Beauty and the Beast", subtitle: "Glass dome, single crimson rose", universe: "Historical Artifacts", category: "Curiosities", notes: "Petals still falling. Prince has until the last petal.", currentValue: 2800000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("rumple", 24), title: "Raven's Feather — Odin's Messenger", subtitle: "Black feather, speaking ability", universe: "Historical Artifacts", category: "Curiosities", notes: "Acquired from Huginn or Muninn — neither will say which.", currentValue: 680000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("rumple", 25), title: "Mermaid Scale Collection", subtitle: "Iridescent scales, various species", universe: "Natural History", category: "Curiosities", notes: "Each scale grants one hour of aquatic breathing.", currentValue: 380000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("rumple", 26), title: "Pandora's Box — Sealed", subtitle: "Pithos vessel, ancient Greek origin", universe: "Historical Artifacts", category: "Curiosities", notes: "All evils of the world. Hope is still inside. DO NOT OPEN.", currentValue: 12000000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("rumple", 27), title: "Prophecy Scroll — Unread", subtitle: "Oracle's parchment, sealed with wax", universe: "Books & Manuscripts", category: "Grimoires", notes: "The seal breaks only when the subject reads it. Filed under 'leverage'.", currentValue: 3200000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("rumple", 28), title: "Thumbelina's Walnut Shell Cradle", subtitle: "Miniature furniture, 2-inch scale", universe: "Historical Artifacts", category: "Curiosities", notes: "Tiny human girl lived in this. Traded for a pea-sized gem.", currentValue: 45000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("rumple", 29), title: "Troll Bridge Toll Book", subtitle: "Ledger of crossings and deals, c. Norse era", universe: "Books & Manuscripts", category: "Historical Documents", notes: "Who crossed, what they paid. Three billy goats: outstanding debt.", currentValue: 95000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("rumple", 30), title: "Peter Pan's Shadow", subtitle: "Detached, sewn back incorrectly", universe: "Historical Artifacts", category: "Curiosities", notes: "Shadow occasionally acts independently. Wendy's stitching visible.", currentValue: 1800000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("rumple", 31), title: "Wolf's Breath — Bottled", subtitle: "Three sealed vials: straw, stick, brick", universe: "Historical Artifacts", category: "Curiosities", notes: "Huffing and puffing capacity sold separately.", currentValue: 180000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("rumple", 32), title: "Ugly Duckling Feather — Swan Transformation", subtitle: "Pinfeather and adult swan quill", universe: "Natural History", category: "Curiosities", notes: "Before and after. Andersen story. Rumple witnessed it.", currentValue: 28000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("rumple", 33), title: "Excalibur Scabbard Fragment", subtitle: "Leather and gold thread, Arthurian", universe: "Historical Artifacts", category: "Arms & Militaria", notes: "The scabbard prevented wounds. Rumple has a piece.", currentValue: 2200000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("rumple", 34), title: "Golden Goose Egg", subtitle: "Solid gold, still warm", universe: "Historical Artifacts", category: "Curiosities", notes: "Daily production stopped when farmer killed the goose. Last egg.", currentValue: 4200000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("rumple", 35), title: "Fairy Godmother Wand", subtitle: "Hazel wood and moonstone", universe: "Historical Artifacts", category: "Curiosities", notes: "Bibbidi-bobbidi-boo. Power fading. Needs recharging.", currentValue: 1600000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("rumple", 36), title: "Rapunzel's Hair Braid", subtitle: "Golden hair, 70 feet", universe: "Historical Artifacts", category: "Curiosities", notes: "Cut by the witch. Still strong enough to support a prince.", currentValue: 380000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("rumple", 37), title: "Faust's Soul Contract", subtitle: "Original deal, Mephistopheles signature", universe: "Books & Manuscripts", category: "Legal Documents", notes: "Rumple admires the craftsmanship. He has a copy for study.", currentValue: 8800000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("rumple", 38), title: "Wish-Granting Monkey's Paw", subtitle: "Preserved, three wishes remaining", universe: "Historical Artifacts", category: "Curiosities", notes: "W.W. Jacobs described it. This is the real one. Be specific.", currentValue: 3600000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("rumple", 39), title: "Neverland Map", subtitle: "Second star to the right, hand-drawn", universe: "Books & Manuscripts", category: "Maps", notes: "Straight on till morning. Island moves. Map occasionally updates.", currentValue: 1200000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("rumple", 40), title: "The Imp's Own Name — Engraved Plate", subtitle: "Gold, locked in a mirror box", universe: "Historical Artifacts", category: "Curiosities", notes: "RUMPELSTILTSKIN. Knowing it breaks every deal. Kept hidden.", currentValue: 22000000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
  ],
  galleries: [
    { id: gid("rumple", 1), title: "The Deal Vault", description: "Everything acquired through a deal. Nothing was free. Every item has a story.", themePack: "midnight", visibility: "PUBLIC", itemIds: Array.from({length:16}, (_, i) => iid("rumple", i+1)) },
    { id: gid("rumple", 2), title: "Enchanted Objects", description: "Cursed, magical, and enchanted artifacts. Touch nothing without asking first.", themePack: "walnut", visibility: "PUBLIC", itemIds: [iid("rumple",3),iid("rumple",5),iid("rumple",6),iid("rumple",7),iid("rumple",10),iid("rumple",11),iid("rumple",23),iid("rumple",26),iid("rumple",30),iid("rumple",34),iid("rumple",38)] },
  ],
};

// ═══════════════════════════════════════════════════════════════
// 19 — WALTON J JR (Indiana Jones inspired)
// ═══════════════════════════════════════════════════════════════
const waltonJJr: SeedCharacter = {
  profileId: "00000000-0000-0000-0000-000000000019",
  displayName: "Walton J. Jr.",
  handle: "waltonjjr",
  avatarEmoji: "🎩",
  bio: "Professor of Archaeology. Field operative. Walton J. Jr. believes that history belongs in a museum — and spends his career making sure it gets there, one dangerous expedition at a time. His collection spans every civilization he has chased across five continents.",
  primaryFocus: "Antiquities",
  items: [
    // Mythical & Religious
    { id: iid("walton", 1), title: "Holy Grail — Pewter Cup", subtitle: "Antioch Chalice style, 4th Century AD", universe: "Antiquities", category: "Religious Artifacts", notes: "The cup of the Last Supper. Simple. Unassuming. As it should be.", currentValue: 22000000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("walton", 2), title: "Ark of the Covenant — Scale Model", subtitle: "Reference model only. The real one is elsewhere.", universe: "Historical Artifacts", category: "Religious Artifacts", notes: "Full-size replica for study purposes. Real one stays where it is.", currentValue: 48000, purchasePrice: 18000, isPublic: true, status: "COLLECTION" },
    { id: iid("walton", 3), title: "Sankara Stone — Third", subtitle: "Shiva lingam stone, Pankot Palace", universe: "Antiquities", category: "Indian", notes: "Recovered from the Thuggee cult. Returns heat when held.", currentValue: 4800000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("walton", 4), title: "Crystal Skull — Akator", subtitle: "Carved quartz crystal, Mayan style", universe: "Antiquities", category: "Pre-Columbian", notes: "Interdimensional origin. Heavy. Slightly uncomfortable to be near.", currentValue: 6200000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("walton", 5), title: "Spear of Destiny — Tip Fragment", subtitle: "Iron, Roman, 1st Century AD", universe: "Historical Artifacts", category: "Religious Artifacts", notes: "The lance that pierced Christ. Whoever holds it controls destiny.", currentValue: 9400000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    // Academic & Field
    { id: iid("walton", 6), title: "Walton's Field Journal — Volume XXII", subtitle: "Leather-bound, Morocco", universe: "Books & Manuscripts", category: "Personal Papers", notes: "Guatemala expedition, 1938. The map is still inside.", currentValue: 85000, purchasePrice: 28000, isPublic: true, status: "COLLECTION" },
    { id: iid("walton", 7), title: "Fedora Hat — Field Grade", subtitle: "Herbert Johnson, London", universe: "Historical Artifacts", category: "Clothing", notes: "The hat. Never goes down without it.", currentValue: 280000, purchasePrice: 95000, isPublic: true, status: "COLLECTION" },
    { id: iid("walton", 8), title: "Bullwhip — 10-foot Plaited", subtitle: "Kangaroo hide, custom braided", universe: "Historical Artifacts", category: "Tools", notes: "Swings across chasms. Wraps around torch brackets. Essential.", currentValue: 45000, purchasePrice: 15000, isPublic: true, status: "COLLECTION" },
    { id: iid("walton", 9), title: "University Tenure Letter — Marshall College", subtitle: "Archaeology Department, 1936", universe: "Books & Manuscripts", category: "Personal Papers", notes: "He keeps forgetting to submit grades. Still has tenure.", currentValue: 4500, purchasePrice: 1500, isPublic: true, status: "COLLECTION" },
    { id: iid("walton", 10), title: "Harrison Ford Honorary Degree", subtitle: "Fictional — from the college prop department", universe: "Books & Manuscripts", category: "Personal Papers", notes: "Walton is Walton. Not saying anything else.", currentValue: 2800, purchasePrice: 1000, isPublic: true, status: "COLLECTION" },
    // Egyptian
    { id: iid("walton", 11), title: "Rosetta Stone Squeeze — Original Impression", subtitle: "Plaster squeeze of hieroglyphic panel", universe: "Antiquities", category: "Egyptian", notes: "Taken in the field. The British Museum has the original.", currentValue: 22000, purchasePrice: 8000, isPublic: true, status: "COLLECTION" },
    { id: iid("walton", 12), title: "Canopic Jar — Hapy Baboon Lid", subtitle: "Egyptian faience, 18th Dynasty", universe: "Antiquities", category: "Egyptian", notes: "Contains preserved organs. Lungs, specifically. Do not open.", currentValue: 48000, purchasePrice: 17000, isPublic: true, status: "COLLECTION" },
    { id: iid("walton", 13), title: "Scarab Pectoral — Lapis and Gold", subtitle: "New Kingdom, c. 1350–1200 BC", universe: "Antiquities", category: "Egyptian", notes: "Broad collar with winged scarab. Tomb excavation, Luxor.", currentValue: 380000, purchasePrice: 135000, isPublic: true, status: "COLLECTION" },
    { id: iid("walton", 14), title: "Mummy's Hand — Intact", subtitle: "Ptolemaic mummification, c. 200 BC", universe: "Antiquities", category: "Egyptian", notes: "Detached during the Cairo incident. Not proud of it.", currentValue: 28000, purchasePrice: 10000, isPublic: true, status: "COLLECTION" },
    // Greek & Roman
    { id: iid("walton", 15), title: "Greek Trireme Bronze Ram", subtitle: "Athens, c. 480 BC", universe: "Antiquities", category: "Greek", notes: "Recovered from the Salamis battle site. Underwater excavation.", currentValue: 680000, purchasePrice: 240000, isPublic: true, status: "COLLECTION" },
    { id: iid("walton", 16), title: "Roman Gladius — Pompeii Type", subtitle: "Iron and bone, 1st Century AD", universe: "Antiquities", category: "Roman", notes: "From a soldier's kit. Pompeii eruption sealed it perfectly.", currentValue: 95000, purchasePrice: 34000, isPublic: true, status: "COLLECTION" },
    { id: iid("walton", 17), title: "Trojan Horse Schematic", subtitle: "Greek papyrus fragment, c. 500 BC", universe: "Books & Manuscripts", category: "Manuscripts", notes: "Engineering diagram. Whether Troy is real — debated. This isn't.", currentValue: 280000, purchasePrice: 98000, isPublic: true, status: "COLLECTION" },
    // Mesoamerican
    { id: iid("walton", 18), title: "Aztec Calendar Stone Rubbing", subtitle: "Life-size paper rubbing, Tenochtitlan", universe: "Books & Manuscripts", category: "Manuscripts", notes: "Not the end of the world. Just a calendar. People misread it.", currentValue: 22000, purchasePrice: 8000, isPublic: true, status: "COLLECTION" },
    { id: iid("walton", 19), title: "Mayan Jade Mask — Death God", subtitle: "Jade mosaic, Palenque, c. 700 AD", universe: "Antiquities", category: "Pre-Columbian", notes: "Burial mask from a Palenque royal tomb.", currentValue: 1800000, purchasePrice: 640000, isPublic: true, status: "COLLECTION" },
    { id: iid("walton", 20), title: "Olmec Colossal Head — Miniature Cast", subtitle: "Basalt reproduction, 1:24 scale", universe: "Historical Artifacts", category: "Models", notes: "Largest heads weigh 40 tons. This one is manageable.", currentValue: 4500, purchasePrice: 1600, isPublic: true, status: "COLLECTION" },
    // Medieval & Arthurian
    { id: iid("walton", 21), title: "Knight Templar Seal — Grand Master", subtitle: "Bronze, c. 1150", universe: "Antiquities", category: "Medieval", notes: "Templars guarded the Grail. Walton found this near Jerusalem.", currentValue: 180000, purchasePrice: 64000, isPublic: true, status: "COLLECTION" },
    { id: iid("walton", 22), title: "Arthurian Round Table Fragment", subtitle: "Oak, c. medieval, Winchester Castle type", universe: "Historical Artifacts", category: "Medieval", notes: "The Winchester table dates to 1290. This shard matches the grain.", currentValue: 85000, purchasePrice: 30000, isPublic: true, status: "COLLECTION" },
    { id: iid("walton", 23), title: "Merlin's Staff — Twisted Hazel", subtitle: "Gnarled wood, rune-carved", universe: "Historical Artifacts", category: "Curiosities", notes: "Acquired from a Welsh monastery. Monks were relieved to see it go.", currentValue: 480000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    // Books & Maps
    { id: iid("walton", 24), title: "Henry Walton Sr.'s Grail Diary", subtitle: "Leather-bound, father's notes", universe: "Books & Manuscripts", category: "Personal Papers", notes: "Three hundred pages of Grail research. Postcards inside.", currentValue: 380000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("walton", 25), title: "Dead Sea Scroll Fragment", subtitle: "Qumran Cave 4, Isaiah text", universe: "Books & Manuscripts", category: "Manuscripts", notes: "Acquired through legitimate channels. The Israeli government disagrees.", currentValue: 2800000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("walton", 26), title: "Navigation Chart — 1513 Piri Reis Map", subtitle: "Facsimile of the Antarctic coastline map", universe: "Books & Manuscripts", category: "Maps", notes: "Depicts Antarctica before it was discovered. Source debated.", currentValue: 28000, purchasePrice: 10000, isPublic: true, status: "COLLECTION" },
    // Asian
    { id: iid("walton", 27), title: "Shang Dynasty Oracle Bone", subtitle: "Inscribed ox scapula, c. 1200 BC", universe: "Antiquities", category: "Chinese", notes: "Divination record. Earliest Chinese writing.", currentValue: 280000, purchasePrice: 98000, isPublic: true, status: "COLLECTION" },
    { id: iid("walton", 28), title: "Silk Road Caravanserai Token", subtitle: "Bronze, Sogdian, c. 700 AD", universe: "Coins & Currency", category: "Ancient Coins", notes: "Used at trading posts along the Silk Road.", currentValue: 8500, purchasePrice: 3000, isPublic: true, status: "COLLECTION" },
    { id: iid("walton", 29), title: "Japanese Katana — Muromachi Period", subtitle: "c. 1350–1573", universe: "Historical Artifacts", category: "Arms & Militaria", notes: "Signed blade. Perfect curvature. Active spirit. Be respectful.", currentValue: 380000, purchasePrice: 135000, isPublic: true, status: "COLLECTION" },
    // African
    { id: iid("walton", 30), title: "Queen of Sheba's Ring", subtitle: "Gold with engraved seal, Ethiopian tradition", universe: "Antiquities", category: "African", notes: "Ethiopian tradition places the Ark in Axum. The ring points there.", currentValue: 1200000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("walton", 31), title: "Great Zimbabwe Bird — Soapstone", subtitle: "Zimbabwe, c. 1200–1400 AD", universe: "Antiquities", category: "African", notes: "One of eight birds. Symbol of the Great Zimbabwe civilization.", currentValue: 680000, purchasePrice: 240000, isPublic: true, status: "COLLECTION" },
    // Field Equipment
    { id: iid("walton", 32), title: "Compass — Brunton Professional", subtitle: "Brass, 1930s field model", universe: "Historical Artifacts", category: "Scientific Instruments", notes: "Used on every expedition since 1933. Still accurate.", currentValue: 4500, purchasePrice: 1600, isPublic: true, status: "COLLECTION" },
    { id: iid("walton", 33), title: "Colt 1917 Revolver", subtitle: ".45 ACP, field worn", universe: "Historical Artifacts", category: "Arms & Militaria", notes: "Standard issue. Reliable. Never as fast as the sword guy.", currentValue: 8500, purchasePrice: 3000, isPublic: true, status: "COLLECTION" },
    { id: iid("walton", 34), title: "Snake — Preserved", subtitle: "Various species, formaldehyde", universe: "Natural History", category: "Animal Specimens", notes: "He hates snakes. Keeps them anyway. Academic interest only.", currentValue: 1200, purchasePrice: 450, isPublic: true, status: "COLLECTION" },
    { id: iid("walton", 35), title: "Dig Site Photograph Album", subtitle: "Black and white, 1930s–1950s", universe: "Books & Manuscripts", category: "Photographs", notes: "Every major dig documented. Colleagues, discoveries, close calls.", currentValue: 18000, purchasePrice: 6500, isPublic: true, status: "COLLECTION" },
    // Viking & Norse
    { id: iid("walton", 36), title: "Viking Runestone — Portable", subtitle: "Limestone, 9th Century, Norse inscription", universe: "Antiquities", category: "Viking", notes: "Carried it from Sweden on his back. Worth it.", currentValue: 145000, purchasePrice: 52000, isPublic: true, status: "COLLECTION" },
    // South American
    { id: iid("walton", 37), title: "El Dorado Gold Mask", subtitle: "Muisca culture, Colombia, c. 1000 AD", universe: "Antiquities", category: "Pre-Columbian", notes: "From the legend of the golden man. Genuine Muisca goldwork.", currentValue: 2400000, purchasePrice: 840000, isPublic: true, status: "COLLECTION" },
    { id: iid("walton", 38), title: "Incan Quipu — Knotted Records", subtitle: "Colored string accounting device, c. 1450", universe: "Antiquities", category: "Pre-Columbian", notes: "Records a tribute payment. Some quipus contain narrative text.", currentValue: 85000, purchasePrice: 30000, isPublic: true, status: "COLLECTION" },
    // Atlantis
    { id: iid("walton", 39), title: "Atlantean Orichalcum Fragment", subtitle: "Unknown metal alloy, pre-historic", universe: "Antiquities", category: "Curiosities", notes: "Plato described orichalcum. This matches no known alloy.", currentValue: 4800000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("walton", 40), title: "Marshall College Lecture Notes — Archaeology 101", subtitle: "Mimeograph, 1938 semester", universe: "Books & Manuscripts", category: "Personal Papers", notes: "Students love him. He is never actually there.", currentValue: 2800, purchasePrice: 1000, isPublic: true, status: "COLLECTION" },
  ],
  galleries: [
    { id: gid("walton", 1), title: "It Belongs in a Museum", description: "Five continents of artifacts, recovered at considerable personal risk.", themePack: "walnut", visibility: "PUBLIC", itemIds: Array.from({length:16}, (_, i) => iid("walton", i+1)) },
    { id: gid("walton", 2), title: "Mythic Relics", description: "The Holy Grail, the Sankara Stones, and other artifacts that science cannot explain.", themePack: "midnight", visibility: "PUBLIC", itemIds: [iid("walton",1),iid("walton",3),iid("walton",4),iid("walton",5),iid("walton",23),iid("walton",30),iid("walton",39)] },
  ],
};

// ═══════════════════════════════════════════════════════════════
// 20 — ERIK (THE PHANTOM)
// ═══════════════════════════════════════════════════════════════
const erik: SeedCharacter = {
  profileId: "00000000-0000-0000-0000-000000000020",
  displayName: "Erik — The Phantom",
  handle: "phantomoftheopera",
  avatarEmoji: "🎭",
  bio: "Composer. Architect. Ghost. Erik built his home beneath the Paris Opéra and composed music that no audience would ever hear — until Christine. His collection spans the music he wrote in darkness, the mask he never removed, and the organs of a genius the world was not ready for.",
  primaryFocus: "Music & Instruments",
  items: [
    { id: iid("erik", 1), title: "The Phantom's White Mask", subtitle: "Porcelain and leather, c. 1880", universe: "Historical Artifacts", category: "Costume & Dress", notes: "Concealing the right side of the face. Never willingly removed.", currentValue: 1800000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("erik", 2), title: "Don Juan Triumphant — Autograph Score", subtitle: "Full opera manuscript, Erik's hand", universe: "Books & Manuscripts", category: "Music Manuscripts", notes: "Composed over twenty years. Performed once. The night everything ended.", currentValue: 4800000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("erik", 3), title: "Pipe Organ — Subterranean", subtitle: "Custom built beneath Paris, c. 1870", universe: "Music & Instruments", category: "Organs", notes: "127 pipes. Plays through the walls of the Opéra above.", currentValue: 2200000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("erik", 4), title: "Christine's Corsage — Dried", subtitle: "White roses, performance night", universe: "Historical Artifacts", category: "Personal Effects", notes: "From her debut performance. He watched from Box 5.", currentValue: 22000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("erik", 5), title: "Punjab Lasso — Silk and Lead", subtitle: "Execution weapon, c. 1880", universe: "Historical Artifacts", category: "Arms & Militaria", notes: "Erik learned this in Persia. Soundless. Effective.", currentValue: 85000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("erik", 6), title: "Paris Opéra Chandelier Counterweight", subtitle: "Iron, Garnier opera house, 1875", universe: "Historical Artifacts", category: "Architectural", notes: "That night. The chandelier. The incident.", currentValue: 280000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("erik", 7), title: "Underground Lake Mirror", subtitle: "Venetian glass, sealed in moisture", universe: "Decorative Arts", category: "Mirrors", notes: "His reflection is the only one he could bear to face.", currentValue: 48000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("erik", 8), title: "Le Fantôme de l'Opéra — Leroux First Edition", subtitle: "Paris, 1910 — serialized then bound", universe: "Books & Manuscripts", category: "Rare Books", notes: "His story. He finds it mostly accurate. The nose detail is wrong.", currentValue: 45000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("erik", 9), title: "Raoul's Engagement Ring — Returned", subtitle: "Diamond solitaire, c. 1880", universe: "Jewelry & Accessories", category: "Rings", notes: "Christine eventually chose Raoul. The ring sat here after.", currentValue: 28000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("erik", 10), title: "Box Five Reserved Card", subtitle: "Paris Opéra, standing reservation", universe: "Books & Manuscripts", category: "Historical Documents", notes: "Every performance. His box. Never to be sold.", currentValue: 8500, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("erik", 11), title: "Persian Black Rope — Execution Style", subtitle: "Silk braided, c. 1880", universe: "Historical Artifacts", category: "Arms & Militaria", notes: "From his years in Persia. Before Paris.", currentValue: 22000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("erik", 12), title: "Architecture Blueprint — Palais Garnier", subtitle: "Charles Garnier's working drawing, 1861", universe: "Books & Manuscripts", category: "Architectural Plans", notes: "Erik helped build it. He knows every passage.", currentValue: 280000, purchasePrice: 85000, isPublic: true, status: "COLLECTION" },
    { id: iid("erik", 13), title: "Ventriloquist's Dummy", subtitle: "Carved wood, dressed in evening clothes", universe: "Historical Artifacts", category: "Curiosities", notes: "Erik could throw his voice anywhere in the Opéra.", currentValue: 18000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("erik", 14), title: "Music Box — Monkey Automaton", subtitle: "Persian craftsmanship, c. 1875", universe: "Science & Technology", category: "Automata", notes: "Plays Masquerade. The monkey's eyes follow you.", currentValue: 45000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("erik", 15), title: "Christine's Voice Lesson Transcript", subtitle: "Handwritten, Angel of Music notation", universe: "Books & Manuscripts", category: "Music Manuscripts", notes: "Breathing exercises in his hand. She thought she heard an angel.", currentValue: 85000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("erik", 16), title: "Death's Head Throne", subtitle: "Carved ebony, skull motifs", universe: "Decorative Arts", category: "Furniture", notes: "In the underground chamber. Where he composed.", currentValue: 95000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("erik", 17), title: "Persian Architecture Certificate", subtitle: "Award from the Shah, c. 1865", universe: "Books & Manuscripts", category: "Historical Documents", notes: "Erik designed palaces for the Shah before fleeing.", currentValue: 45000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("erik", 18), title: "Trapdoor Mechanism Blueprint", subtitle: "Erik's own engineering drawing", universe: "Books & Manuscripts", category: "Architectural Plans", notes: "Twenty-three trapdoors in the Opéra. He designed seventeen.", currentValue: 65000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("erik", 19), title: "Carnival Mask — Red Death Style", subtitle: "Painted papier-mâché, c. 1880", universe: "Historical Artifacts", category: "Costume & Dress", notes: "The masquerade ball. His entrance. Their first real meeting.", currentValue: 22000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("erik", 20), title: "Meyerbeer Opera Score — Annotated", subtitle: "Robert le Diable, heavily marked", universe: "Books & Manuscripts", category: "Sheet Music", notes: "Erik studied every major opera. His annotations are themselves art.", currentValue: 18000, purchasePrice: 6500, isPublic: true, status: "COLLECTION" },
    { id: iid("erik", 21), title: "Christine's Mirror — Passage Door", subtitle: "Full-length, hinged on secret pivot", universe: "Historical Artifacts", category: "Architectural", notes: "The mirror that was also a door. To his world.", currentValue: 85000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("erik", 22), title: "Candle Sconce — Underground Chamber", subtitle: "Iron, set into stone, c. 1870", universe: "Historical Artifacts", category: "Lighting", notes: "Hundreds of candles lit his underground home.", currentValue: 4500, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("erik", 23), title: "Barrel Organ — Street Musician Style", subtitle: "Mechanical, c. 1860", universe: "Music & Instruments", category: "Mechanical Music", notes: "Erik's disguise for moving above ground.", currentValue: 12000, purchasePrice: 4000, isPublic: true, status: "COLLECTION" },
    { id: iid("erik", 24), title: "Stradivarius Violin — Unplayed", subtitle: "c. 1715 — Cremona", universe: "Music & Instruments", category: "Stringed Instruments", notes: "He preferred keyboard. But kept this because it was perfect.", currentValue: 1800000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("erik", 25), title: "Secret Passageway Map — Full Opera", subtitle: "Erik's own diagram", universe: "Books & Manuscripts", category: "Maps", notes: "Every hidden corridor, secret door, and spy hole.", currentValue: 95000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("erik", 26), title: "Faust Score — Gounod", subtitle: "First edition, Paris 1859", universe: "Books & Manuscripts", category: "Sheet Music", notes: "The opera running the night of the chandelier incident.", currentValue: 28000, purchasePrice: 9500, isPublic: true, status: "COLLECTION" },
    { id: iid("erik", 27), title: "Gold Ring — Never Given", subtitle: "Plain band, intended for Christine", universe: "Jewelry & Accessories", category: "Rings", notes: "He had it made. She never knew.", currentValue: 18000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("erik", 28), title: "Opera Ghost Letter — To Management", subtitle: "Handwritten, threatening tone", universe: "Books & Manuscripts", category: "Personal Papers", notes: "Demanding his salary of 20,000 francs per month.", currentValue: 22000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("erik", 29), title: "Magic Lasso Instruction Scroll", subtitle: "Persian text, translated by Erik", universe: "Books & Manuscripts", category: "Manuscripts", notes: "The technique for the Punjab lasso. His Persian years.", currentValue: 28000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("erik", 30), title: "Torture Chamber Switch — Iron Lever", subtitle: "Activated the rotating mirror room", universe: "Historical Artifacts", category: "Architectural", notes: "The heat, the mirrors, the jungle wallpaper. His darkest invention.", currentValue: 22000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("erik", 31), title: "Phantom of the Opera — Broadway Playbill", subtitle: "1988 opening night, Majestic Theatre", universe: "Film & Entertainment", category: "Programs", notes: "Andrew Lloyd Webber's adaptation. Still running.", currentValue: 1800, purchasePrice: 650, isPublic: true, status: "COLLECTION" },
    { id: iid("erik", 32), title: "Lon Chaney Makeup Notes", subtitle: "Universal Studios, 1925", universe: "Film & Entertainment", category: "Film Artifacts", notes: "How Chaney created the Phantom's sunken face. Self-inflicted.", currentValue: 28000, purchasePrice: 9500, isPublic: true, status: "COLLECTION" },
    { id: iid("erik", 33), title: "Piano Sheet — Point of No Return", subtitle: "Autograph manuscript, Erik's hand", universe: "Books & Manuscripts", category: "Music Manuscripts", notes: "The most dangerous duet ever written.", currentValue: 280000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("erik", 34), title: "Underground Lake Gondola", subtitle: "Scale model, carved wood, c. 1880", universe: "Decorative Arts", category: "Models", notes: "The lake beneath the Opéra. He poled it himself.", currentValue: 12000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("erik", 35), title: "Ballet Slipper — Meg Giry", subtitle: "Pink satin, signed", universe: "Historical Artifacts", category: "Costume & Dress", notes: "Madame Giry's daughter. She believed in him when others didn't.", currentValue: 4500, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("erik", 36), title: "Persian Iron Mask Fragment", subtitle: "Punishment device, c. 1865", universe: "Historical Artifacts", category: "Arms & Militaria", notes: "From the Shah's torture prison. Where Erik was kept before escaping.", currentValue: 45000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("erik", 37), title: "Composition Desk — Underground", subtitle: "Mahogany writing table, c. 1870", universe: "Decorative Arts", category: "Furniture", notes: "Where Don Juan Triumphant was written. Ink stains in the grain.", currentValue: 48000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("erik", 38), title: "Mirrored Ball — Masquerade", subtitle: "Crystal and silver, c. 1880", universe: "Decorative Arts", category: "Decorative Objects", notes: "From the Opéra's grand staircase ball.", currentValue: 18000, purchasePrice: 6000, isPublic: true, status: "COLLECTION" },
    { id: iid("erik", 39), title: "Sheet Music Stand — Wrought Iron", subtitle: "Custom, c. 1875", universe: "Music & Instruments", category: "Musical Accessories", notes: "Holds the score steady. Used for every composition session.", currentValue: 4500, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("erik", 40), title: "The Angel of Music — Final Note", subtitle: "Last composition, 1881", universe: "Books & Manuscripts", category: "Music Manuscripts", notes: "Written the night Christine left. Twelve bars. Unfinished.", currentValue: 2800000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
  ],
  galleries: [
    { id: gid("erik", 1), title: "Below the Opera", description: "The music, masks, and artifacts of a genius who lived in darkness.", themePack: "midnight", visibility: "PUBLIC", itemIds: Array.from({length:16}, (_, i) => iid("erik", i+1)) },
    { id: gid("erik", 2), title: "Don Juan Triumphant", description: "The manuscripts and instruments of an opera that was never meant to be heard.", themePack: "classic", visibility: "PUBLIC", itemIds: [iid("erik",2),iid("erik",3),iid("erik",15),iid("erik",24),iid("erik",33),iid("erik",40)] },
  ],
};

// ═══════════════════════════════════════════════════════════════
// 21 — SOLOMON KING (The Blues Legend)
// ═══════════════════════════════════════════════════════════════
const solomonKing: SeedCharacter = {
  profileId: "00000000-0000-0000-0000-000000000021",
  displayName: "Solomon King",
  handle: "solomonking",
  avatarEmoji: "🎸",
  bio: "Delta blues. Crossroads. Solomon King showed up in Mississippi in 1929 playing guitar nobody had ever heard before. Some said he sold his soul to get that sound. Solomon never confirmed or denied. He died at 27 under circumstances nobody could explain. The music speaks for itself.",
  primaryFocus: "Music & Instruments",
  items: [
    // Instruments
    { id: iid("solo", 1), title: "1928 National Style O Resonator Guitar", subtitle: "Steel body, Hawaiian lap steel tuning", universe: "Music & Instruments", category: "Guitars", notes: "The guitar. Played at the crossroads. Never needed tuning after that night.", currentValue: 485000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("solo", 2), title: "Slide — Bottleneck Glass", subtitle: "Broken Midnight Special bottle, 1930", universe: "Music & Instruments", category: "Guitar Accessories", notes: "Cut from a whiskey bottle. The tone was never replicated.", currentValue: 28000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("solo", 3), title: "1931 Gibson L-1 Flat-Top Guitar", subtitle: "The second guitar. For recording.", universe: "Music & Instruments", category: "Guitars", notes: "Used for the Grafton sessions. Spruce top, mahogany back.", currentValue: 185000, purchasePrice: 85000, isPublic: true, status: "COLLECTION" },
    { id: iid("solo", 4), title: "Harmonica — Hohner Marine Band Key of A", subtitle: "c. 1928", universe: "Music & Instruments", category: "Harmonicas", notes: "Second instrument. Played simultaneously in the early juke joints.", currentValue: 8500, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    // Crossroads
    { id: iid("solo", 5), title: "Crossroads Dirt — Dockery Plantation", subtitle: "Sealed glass vial, Mississippi clay", universe: "Historical Artifacts", category: "Curiosities", notes: "From the exact intersection. Collected midnight. Still warm.", currentValue: 22000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("solo", 6), title: "Tuning Peg — Replaced at the Crossroads", subtitle: "Original machine head, steel", universe: "Historical Artifacts", category: "Curiosities", notes: "The old tuning peg. Replaced by a stranger at midnight.", currentValue: 45000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("solo", 7), title: "Contract — Written in the Dirt", subtitle: "Photograph of ground markings, 1930", universe: "Books & Manuscripts", category: "Photographs", notes: "Farmhand photographed the markings at dawn. Still unexplained.", currentValue: 85000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    // Recordings
    { id: iid("solo", 8), title: "78 RPM Record — Cross Road Blues", subtitle: "Vocalion 03519, 1936", universe: "Music & Instruments", category: "Vinyl Records", notes: "Original pressing. Transferred from a single session in San Antonio.", currentValue: 95000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("solo", 9), title: "78 RPM — Hellhound on My Trail", subtitle: "Vocalion 03623, 1937", universe: "Music & Instruments", category: "Vinyl Records", notes: "The most haunted three minutes in American music.", currentValue: 95000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("solo", 10), title: "Recording Session Receipt — Grafton Wisconsin", subtitle: "Paramount Records, 1929", universe: "Books & Manuscripts", category: "Historical Documents", notes: "Payment stub. $20 for two sides. The session that started everything.", currentValue: 22000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("solo", 11), title: "78 RPM — Love in Vain", subtitle: "Vocalion 04630, 1937", universe: "Music & Instruments", category: "Vinyl Records", notes: "Slow blues. Rolling Stones covered it. Nothing matched the original.", currentValue: 85000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("solo", 12), title: "78 RPM — Me and the Devil Blues", subtitle: "Vocalion 04108, 1937", universe: "Music & Instruments", category: "Vinyl Records", notes: "'Early this mornin' you knocked upon my door.' First line.", currentValue: 85000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    // Personal
    { id: iid("solo", 13), title: "Solomon King's Photograph — Only Known", subtitle: "Gelatin silver, c. 1935", universe: "Books & Manuscripts", category: "Photographs", notes: "One of two confirmed photographs. Coin-operated machine, dime store.", currentValue: 180000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("solo", 14), title: "Death Certificate — August 16, 1938", subtitle: "Leflore County, Mississippi", universe: "Books & Manuscripts", category: "Historical Documents", notes: "Cause: unknown. Age: 27. Some say poison. Some say something else.", currentValue: 45000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("solo", 15), title: "Traveling Suit — Brown Wool", subtitle: "c. 1930s, Southern style", universe: "Historical Artifacts", category: "Clothing", notes: "Solomon dressed sharp. Always. Even in juke joints.", currentValue: 18000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("solo", 16), title: "Juke Joint Sign — Three Forks", subtitle: "Painted wood, c. 1930s", universe: "Historical Artifacts", category: "Signs", notes: "The Three Forks Store in Greenwood. Where he played his last show.", currentValue: 22000, purchasePrice: 8000, isPublic: true, status: "COLLECTION" },
    // Delta Context
    { id: iid("solo", 17), title: "Dockery Plantation Work Card", subtitle: "Sunflower County, Mississippi, c. 1910", universe: "Books & Manuscripts", category: "Historical Documents", notes: "Dockery Plantation was where the Delta blues was born.", currentValue: 8500, purchasePrice: 3000, isPublic: true, status: "COLLECTION" },
    { id: iid("solo", 18), title: "Mississippi Delta Map — 1930", subtitle: "Hand-drawn county boundaries", universe: "Books & Manuscripts", category: "Maps", notes: "The birthplace. Every name on this map is a blues song.", currentValue: 12000, purchasePrice: 4500, isPublic: true, status: "COLLECTION" },
    { id: iid("solo", 19), title: "Sharecropper's Ledger", subtitle: "Sunflower County, 1920s", universe: "Books & Manuscripts", category: "Historical Documents", notes: "The system that kept Black farmers in debt forever. Context.", currentValue: 8500, purchasePrice: 3000, isPublic: true, status: "COLLECTION" },
    { id: iid("solo", 20), title: "Jim Crow Railroad Car Notice", subtitle: "Illinois Central, c. 1920", universe: "Books & Manuscripts", category: "Historical Documents", notes: "Separate cars. Solomon rode them north to Chicago eventually.", currentValue: 4500, purchasePrice: 1600, isPublic: true, status: "COLLECTION" },
    // Great Migration
    { id: iid("solo", 21), title: "Chicago Defender Newspaper", subtitle: "January 1917 — calling Black Southerners north", universe: "Books & Manuscripts", category: "Newspapers", notes: "The paper that advertised the Great Migration. Solomon read it.", currentValue: 8500, purchasePrice: 3000, isPublic: true, status: "COLLECTION" },
    { id: iid("solo", 22), title: "Illinois Central Train Ticket — Jackson to Chicago", subtitle: "c. 1930s", universe: "Historical Artifacts", category: "Travel", notes: "The route north. Blues musicians followed it to Chess Records.", currentValue: 4500, purchasePrice: 1600, isPublic: true, status: "COLLECTION" },
    // Other blues instruments and artifacts
    { id: iid("solo", 23), title: "Washboard — Rhythm Instrument", subtitle: "Zinc, c. 1920", universe: "Music & Instruments", category: "Percussion", notes: "Used in early jug band sessions. Pre-drum kit blues percussion.", currentValue: 4500, purchasePrice: 1600, isPublic: true, status: "COLLECTION" },
    { id: iid("solo", 24), title: "Jug — Moonshine Vessel / Instrument", subtitle: "Stoneware, c. 1920", universe: "Music & Instruments", category: "Curiosities", notes: "Blowing across the mouth creates bass tones. Jug bands.", currentValue: 4500, purchasePrice: 1600, isPublic: true, status: "COLLECTION" },
    { id: iid("solo", 25), title: "Sonny Boy Williamson's Harmonica", subtitle: "Hohner chromatic, c. 1935", universe: "Music & Instruments", category: "Harmonicas", notes: "Acquired through trade. Sonny Boy played Chicago blues.", currentValue: 22000, purchasePrice: 8000, isPublic: true, status: "COLLECTION" },
    { id: iid("solo", 26), title: "Clarksdale Juke Joint Photograph", subtitle: "Silver gelatin print, c. 1935", universe: "Books & Manuscripts", category: "Photographs", notes: "Saturday night. Dancers visible. Music happening.", currentValue: 12000, purchasePrice: 4500, isPublic: true, status: "COLLECTION" },
    { id: iid("solo", 27), title: "Blues Lyric Notebook", subtitle: "Composition book, pencil", universe: "Books & Manuscripts", category: "Notebooks", notes: "Draft lyrics. Some became recordings. Some are better left here.", currentValue: 95000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    // Rock and Roll Legacy
    { id: iid("solo", 28), title: "Eric Clapton Letter — On the Blues", subtitle: "Personal letter, 1968", universe: "Books & Manuscripts", category: "Autographs", notes: "Clapton credits the Delta masters as his foundation.", currentValue: 28000, purchasePrice: 10000, isPublic: true, status: "COLLECTION" },
    { id: iid("solo", 29), title: "Rolling Stones — Love in Vain Single", subtitle: "Decca Records, 1969", universe: "Music & Instruments", category: "Vinyl Records", notes: "Their cover. Solomon wrote it in 1937.", currentValue: 4500, purchasePrice: 1600, isPublic: true, status: "COLLECTION" },
    { id: iid("solo", 30), title: "Led Zeppelin Borrowed Melody Notice", subtitle: "Copyright filing, c. 1970", universe: "Books & Manuscripts", category: "Legal Documents", notes: "Whole Lotta Love owes something to Solomon's Terraplane Blues.", currentValue: 8500, purchasePrice: 3000, isPublic: true, status: "COLLECTION" },
    // Supernatural elements
    { id: iid("solo", 31), title: "Black Cat Bone", subtitle: "Hoodoo folk object, Mississippi", universe: "Historical Artifacts", category: "Folk Magic", notes: "Lucky charm of the Delta. Carried by bluesman for protection.", currentValue: 4500, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("solo", 32), title: "High John the Conqueror Root", subtitle: "Jalap root, folk magic", universe: "Historical Artifacts", category: "Folk Magic", notes: "Conjure root. Protection against evil. Standard issue in 1930s Mississippi.", currentValue: 2800, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("solo", 33), title: "Crossroads Sign — Highway 61 and 49", subtitle: "Replica of the Clarksdale intersection marker", universe: "Historical Artifacts", category: "Signs", notes: "The actual crossroads. Every blues pilgrimage ends here.", currentValue: 4500, purchasePrice: 1600, isPublic: true, status: "COLLECTION" },
    // Other instruments
    { id: iid("solo", 34), title: "Cigar Box Guitar — Homemade", subtitle: "Three-string, c. 1920", universe: "Music & Instruments", category: "Guitars", notes: "How it started. Before you could buy a guitar, you built one.", currentValue: 8500, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
    { id: iid("solo", 35), title: "Vocalion Record Label — Blanks", subtitle: "Unused record labels, 1930s", universe: "Historical Artifacts", category: "Music Ephemera", notes: "The label that pressed all the early blues sides.", currentValue: 4500, purchasePrice: 1600, isPublic: true, status: "COLLECTION" },
    // Context and legacy
    { id: iid("solo", 36), title: "W.C. Handy — Blues Publication", subtitle: "Memphis Blues sheet music, 1912", universe: "Books & Manuscripts", category: "Sheet Music", notes: "First published blues song. Before the Delta recordings.", currentValue: 8500, purchasePrice: 3000, isPublic: true, status: "COLLECTION" },
    { id: iid("solo", 37), title: "Muddy Waters Chess Records Contract", subtitle: "1948 — Chicago blues era", universe: "Books & Manuscripts", category: "Historical Documents", notes: "The bridge from Delta to Chicago. Solomon came first.", currentValue: 22000, purchasePrice: 8000, isPublic: true, status: "COLLECTION" },
    { id: iid("solo", 38), title: "Dust Bowl Photograph — Mississippi 1930s", subtitle: "Farm Security Administration", universe: "Books & Manuscripts", category: "Photographs", notes: "The world Solomon sang about. Poverty and heat and hope.", currentValue: 8500, purchasePrice: 3000, isPublic: true, status: "COLLECTION" },
    { id: iid("solo", 39), title: "Club Ebony Poster — Indianola Mississippi", subtitle: "c. 1935", universe: "Historical Artifacts", category: "Posters", notes: "B.B. King's home venue. Solomon played there first.", currentValue: 4500, purchasePrice: 1600, isPublic: true, status: "COLLECTION" },
    { id: iid("solo", 40), title: "Last Known Residence Deed", subtitle: "Greenwood, Mississippi, 1938", universe: "Books & Manuscripts", category: "Historical Documents", notes: "A rented room. He had $3.40 when he died. The music was worth more.", currentValue: 18000, purchasePrice: 0, isPublic: true, status: "COLLECTION" },
  ],
  galleries: [
    { id: gid("solo", 1), title: "The Crossroads Collection", description: "Instruments, recordings, and artifacts from the man who changed American music.", themePack: "classic", visibility: "PUBLIC", itemIds: Array.from({length:16}, (_, i) => iid("solo", i+1)) },
    { id: gid("solo", 2), title: "78s and Vinyl", description: "Original pressings of the rarest records in American music history.", themePack: "walnut", visibility: "PUBLIC", itemIds: [iid("solo",8),iid("solo",9),iid("solo",11),iid("solo",12),iid("solo",29)] },
  ],
};

// ═══════════════════════════════════════════════════════════════
// 22 — KAI STERLING (Modern Collector)
// ═══════════════════════════════════════════════════════════════
const kaiSterling: SeedCharacter = {
  profileId: "00000000-0000-0000-0000-000000000022",
  displayName: "Kai Sterling",
  handle: "kaisterling",
  avatarEmoji: "💎",
  bio: "28. Tech exit at 24. Now full-time collector. Kai Sterling built a crypto payments platform, sold it, and spent the next four years building the most aggressive modern collection on the planet — PSA 10 rookie cards, key issue comics, graded games, rare sneakers, and pop culture icons.",
  primaryFocus: "Sports Cards",
  items: [
    // Sports Cards
    { id: iid("kai", 1), title: "LeBron James — 2003 Topps Chrome RC", subtitle: "PSA 10 Gem Mint", universe: "Sports Cards", category: "Basketball Cards", notes: "The King's rookie. Population of 10 PSA 10s.", currentValue: 1800000, purchasePrice: 620000, isPublic: true, status: "COLLECTION" },
    { id: iid("kai", 2), title: "Michael Jordan — 1986 Fleer RC", subtitle: "PSA 10 Gem Mint", universe: "Sports Cards", category: "Basketball Cards", notes: "The most iconic basketball card ever printed.", currentValue: 738000, purchasePrice: 250000, isPublic: true, status: "COLLECTION" },
    { id: iid("kai", 3), title: "Patrick Mahomes — 2017 Panini National Treasures RC Patch Auto", subtitle: "BGS 9.5 / 10 Subs — /99", universe: "Sports Cards", category: "Football Cards", notes: "Patch visible from the game-worn jersey. Low serial.", currentValue: 4800000, purchasePrice: 1600000, isPublic: true, status: "COLLECTION" },
    { id: iid("kai", 4), title: "Mickey Mantle — 1952 Topps #311", subtitle: "PSA 9 Mint", universe: "Sports Cards", category: "Baseball Cards", notes: "The card that started the hobby. High series print.", currentValue: 5200000, purchasePrice: 1800000, isPublic: true, status: "COLLECTION" },
    { id: iid("kai", 5), title: "Wayne Gretzky — 1979 O-Pee-Chee RC", subtitle: "PSA 10 Gem Mint", universe: "Sports Cards", category: "Hockey Cards", notes: "The Great One's rookie. Highest graded example.", currentValue: 3700000, purchasePrice: 1200000, isPublic: true, status: "COLLECTION" },
    { id: iid("kai", 6), title: "Shohei Ohtani — 2018 Bowman Chrome Auto RC", subtitle: "PSA 10 Gem Mint — /499", universe: "Sports Cards", category: "Baseball Cards", notes: "Two-way generational talent. Auto on the card.", currentValue: 185000, purchasePrice: 62000, isPublic: true, status: "COLLECTION" },
    { id: iid("kai", 7), title: "Victor Wembanyama — 2023 Panini Prizm RC", subtitle: "PSA 10 Gold Prizm /10", universe: "Sports Cards", category: "Basketball Cards", notes: "The alien. First card from the Spurs era.", currentValue: 95000, purchasePrice: 32000, isPublic: true, status: "COLLECTION" },
    { id: iid("kai", 8), title: "Tom Brady — 2000 Bowman Chrome RC", subtitle: "BGS 9.5 Gem Mint", universe: "Sports Cards", category: "Football Cards", notes: "GOAT's rookie. 7 Super Bowls. One card.", currentValue: 480000, purchasePrice: 165000, isPublic: true, status: "COLLECTION" },
    // Pokemon
    { id: iid("kai", 9), title: "Pikachu Illustrator Card", subtitle: "CoroCoro Comics, Japan, 1998 — PSA 7", universe: "Trading Cards", category: "Pokémon", notes: "Rarest Pokémon card in existence. Fewer than 40 known.", currentValue: 5300000, purchasePrice: 1800000, isPublic: true, status: "COLLECTION" },
    { id: iid("kai", 10), title: "Charizard — 1999 Base Set 1st Edition", subtitle: "PSA 10 Gem Mint", universe: "Trading Cards", category: "Pokémon", notes: "The card that defined a generation.", currentValue: 420000, purchasePrice: 145000, isPublic: true, status: "COLLECTION" },
    { id: iid("kai", 11), title: "Blastoise — 1999 Base Set 1st Edition", subtitle: "PSA 10 Gem Mint", universe: "Trading Cards", category: "Pokémon", notes: "Shadowless, 1st edition. Pop 3 in PSA 10.", currentValue: 95000, purchasePrice: 32000, isPublic: true, status: "COLLECTION" },
    { id: iid("kai", 12), title: "Lugia — 2000 Neo Genesis 1st Edition", subtitle: "PSA 10 Gem Mint", universe: "Trading Cards", category: "Pokémon", notes: "Silver bird. Fan favorite. Extremely scarce in 10.", currentValue: 180000, purchasePrice: 62000, isPublic: true, status: "COLLECTION" },
    // Comics
    { id: iid("kai", 13), title: "Amazing Fantasy #15", subtitle: "First appearance of Spider-Man, 1962 — CGC 8.0", universe: "Comics", category: "Silver Age", notes: "The most important Silver Age key issue.", currentValue: 1200000, purchasePrice: 420000, isPublic: true, status: "COLLECTION" },
    { id: iid("kai", 14), title: "Incredible Hulk #181", subtitle: "First full appearance of Wolverine, 1974 — CGC 9.8", universe: "Comics", category: "Bronze Age", notes: "Wolverine's first full issue. Population of 1 in CGC 9.8.", currentValue: 380000, purchasePrice: 130000, isPublic: true, status: "COLLECTION" },
    { id: iid("kai", 15), title: "New Mutants #98", subtitle: "First appearance of Deadpool, 1991 — CGC 9.9", universe: "Comics", category: "Modern Age", notes: "Highest graded copy. Only one CGC 9.9 exists.", currentValue: 180000, purchasePrice: 62000, isPublic: true, status: "COLLECTION" },
    { id: iid("kai", 16), title: "Batman #1", subtitle: "1940 — First solo Batman issue — CGC 5.5", universe: "Comics", category: "Golden Age", notes: "Joker and Catwoman both debut here.", currentValue: 2200000, purchasePrice: 760000, isPublic: true, status: "COLLECTION" },
    // Video Games
    { id: iid("kai", 17), title: "Super Mario Bros — NES Cartridge", subtitle: "Wata 9.8 A++ Sealed, 1985", universe: "Video Games", category: "Nintendo NES", notes: "Most valuable video game ever sold. World record.", currentValue: 2000000, purchasePrice: 680000, isPublic: true, status: "COLLECTION" },
    { id: iid("kai", 18), title: "The Legend of Zelda — NES Cartridge", subtitle: "Wata 9.0 A Sealed, 1987", universe: "Video Games", category: "Nintendo NES", notes: "Gold cartridge. First run. Rev-A sticker.", currentValue: 870000, purchasePrice: 295000, isPublic: true, status: "COLLECTION" },
    { id: iid("kai", 19), title: "Pokémon Red — Game Boy Cartridge", subtitle: "Wata 9.4 A+ Sealed, 1998", universe: "Video Games", category: "Nintendo Game Boy", notes: "First English language Pokémon game. High grade.", currentValue: 84000, purchasePrice: 28000, isPublic: true, status: "COLLECTION" },
    { id: iid("kai", 20), title: "Stadium Events — NES Cartridge", subtitle: "Wata 9.2 A Sealed, 1987", universe: "Video Games", category: "Nintendo NES", notes: "Rarest mainstream NES game. Only 200 sold before recall.", currentValue: 1600000, purchasePrice: 545000, isPublic: true, status: "COLLECTION" },
    // Sneakers
    { id: iid("kai", 21), title: "Air Jordan 1 — Chicago Colorway", subtitle: "Nike, 1985 — DS Size 11", universe: "Sneakers", category: "Air Jordan", notes: "Original 1985. Not a retro. Pre-Swoosh. Deadstock.", currentValue: 180000, purchasePrice: 62000, isPublic: true, status: "COLLECTION" },
    { id: iid("kai", 22), title: "Nike Mag — Back to the Future II", subtitle: "Self-lacing, 2016 — #0001/89", universe: "Sneakers", category: "Nike", notes: "First pair. Auctioned for Michael J. Fox Foundation.", currentValue: 85000, purchasePrice: 28000, isPublic: true, status: "COLLECTION" },
    { id: iid("kai", 23), title: "Kanye West x Adidas Yeezy 350 V1 'Turtle Dove'", subtitle: "DS Size 10, 2015", universe: "Sneakers", category: "Adidas", notes: "First Yeezy 350. Signed by Kanye on insole.", currentValue: 48000, purchasePrice: 16000, isPublic: true, status: "COLLECTION" },
    { id: iid("kai", 24), title: "Travis Scott x Air Jordan 1 Retro High OG", subtitle: "DS Size 11, 2019", universe: "Sneakers", category: "Air Jordan", notes: "Backwards Swoosh. Sold out in seconds. No restocks.", currentValue: 4800, purchasePrice: 1600, isPublic: true, status: "COLLECTION" },
    // Pop Culture
    { id: iid("kai", 25), title: "Iron Man Helmet — Mark III", subtitle: "Hero prop, Marvel Studios, 2008", universe: "Film & Entertainment", category: "Props", notes: "Screen-used prop from the first Iron Man film.", currentValue: 180000, purchasePrice: 62000, isPublic: true, status: "COLLECTION" },
    { id: iid("kai", 26), title: "Star Wars — First Edition Kenner Action Figures", subtitle: "Complete set of 12, 1977 — MOC", universe: "Toys & Figures", category: "Star Wars", notes: "Early Bird set. All 12 figures sealed on original cards.", currentValue: 485000, purchasePrice: 165000, isPublic: true, status: "COLLECTION" },
    { id: iid("kai", 27), title: "Original iPhone — First Generation", subtitle: "Factory sealed, 4GB, 2007", universe: "Science & Technology", category: "Consumer Electronics", notes: "The phone that changed everything. Factory sealed.", currentValue: 58000, purchasePrice: 20000, isPublic: true, status: "COLLECTION" },
    { id: iid("kai", 28), title: "Bitcoin Pizza Transaction Screenshot", subtitle: "May 22, 2010 — framed print", universe: "Historical Artifacts", category: "Crypto History", notes: "10,000 BTC for two pizzas. Bitcoin Pizza Day.", currentValue: 18000, purchasePrice: 6500, isPublic: true, status: "COLLECTION" },
    // Modern Art
    { id: iid("kai", 29), title: "Banksy — Girl with Balloon", subtitle: "Signed screenprint, 2004", universe: "Fine Art", category: "Contemporary Art", notes: "Original signed Banksy. Not the shredded version.", currentValue: 480000, purchasePrice: 165000, isPublic: true, status: "COLLECTION" },
    { id: iid("kai", 30), title: "KAWS Companion — Original Fake", subtitle: "Vinyl figure, 2006 — sealed", universe: "Toys & Figures", category: "Designer Toys", notes: "First major KAWS companion. Gray colorway.", currentValue: 48000, purchasePrice: 16000, isPublic: true, status: "COLLECTION" },
    // Music
    { id: iid("kai", 31), title: "Kendrick Lamar — To Pimp a Butterfly", subtitle: "Promo vinyl, 2015 — signed", universe: "Music & Instruments", category: "Vinyl Records", notes: "Signed by Kendrick. Promotional copy with alternate art.", currentValue: 18000, purchasePrice: 6500, isPublic: true, status: "COLLECTION" },
    { id: iid("kai", 32), title: "Taylor Swift — Folklore First Press", subtitle: "Signed vinyl, 2020", universe: "Music & Instruments", category: "Vinyl Records", notes: "Album of the year. First pressing. Signed at release.", currentValue: 8500, purchasePrice: 3000, isPublic: true, status: "COLLECTION" },
    // Sports Memorabilia
    { id: iid("kai", 33), title: "Michael Jordan Game-Worn Shorts — 1996 Finals", subtitle: "JSA authenticated", universe: "Sports Memorabilia", category: "Game Worn", notes: "Game 6 of the 1996 NBA Finals. Championship shorts.", currentValue: 380000, purchasePrice: 130000, isPublic: true, status: "COLLECTION" },
    { id: iid("kai", 34), title: "Serena Williams — 2015 Wimbledon Racket", subtitle: "Match used, signed, PSA/DNA", universe: "Sports Memorabilia", category: "Tennis", notes: "Calendar Slam year. Used in the final match.", currentValue: 48000, purchasePrice: 16000, isPublic: true, status: "COLLECTION" },
    // NFT / Digital
    { id: iid("kai", 35), title: "CryptoPunk #7804", subtitle: "Physical print of Alien Punk, numbered", universe: "Science & Technology", category: "Digital Art", notes: "One of 9 alien CryptoPunks. Kai owns the print rights.", currentValue: 7500000, purchasePrice: 2600000, isPublic: true, status: "COLLECTION" },
    // More cards
    { id: iid("kai", 36), title: "Luka Doncic — 2018 Panini Prizm Rookie Auto", subtitle: "PSA 10 — /25 Gold", universe: "Sports Cards", category: "Basketball Cards", notes: "Serial /25. Auto on-card. Luka's Mavs era.", currentValue: 95000, purchasePrice: 32000, isPublic: true, status: "COLLECTION" },
    { id: iid("kai", 37), title: "Connor McDavid — 2015 Upper Deck Young Guns RC", subtitle: "PSA 10 Gem Mint", universe: "Sports Cards", category: "Hockey Cards", notes: "The next Gretzky. Population of 5 in PSA 10.", currentValue: 85000, purchasePrice: 28000, isPublic: true, status: "COLLECTION" },
    { id: iid("kai", 38), title: "Messi — 2004 Panini Primera División RC Sticker", subtitle: "PSA 10 Gem Mint", universe: "Sports Cards", category: "Soccer Cards", notes: "Rarest Messi rookie. Spanish sticker format.", currentValue: 850000, purchasePrice: 290000, isPublic: true, status: "COLLECTION" },
    // Watches
    { id: iid("kai", 39), title: "Patek Philippe Nautilus 5711 — Green Dial", subtitle: "Final production run, 2021", universe: "Jewelry & Accessories", category: "Watches", notes: "Discontinued final run. Already worth 3x retail.", currentValue: 480000, purchasePrice: 165000, isPublic: true, status: "COLLECTION" },
    { id: iid("kai", 40), title: "AP Royal Oak — 50th Anniversary", subtitle: "Audemars Piguet, titanium, 2022", universe: "Jewelry & Accessories", category: "Watches", notes: "Gerald Genta's design. 50 years. Titanium special edition.", currentValue: 185000, purchasePrice: 62000, isPublic: true, status: "COLLECTION" },
  ],
  galleries: [
    { id: gid("kai", 1), title: "The Modern Vault", description: "PSA 10 rookies, key issue comics, graded games, and rare sneakers from the new golden age of collecting.", themePack: "cold-blue", visibility: "PUBLIC", itemIds: Array.from({length:16}, (_, i) => iid("kai", i+1)) },
    { id: gid("kai", 2), title: "Rookie Cards", description: "The finest rookie card collection in any private vault — PSA 10s only.", themePack: "midnight", visibility: "PUBLIC", itemIds: [iid("kai",1),iid("kai",2),iid("kai",3),iid("kai",4),iid("kai",5),iid("kai",6),iid("kai",7),iid("kai",8),iid("kai",36),iid("kai",37),iid("kai",38)] },
    { id: gid("kai", 3), title: "Key Issues", description: "First appearances, origin issues, and the comics that changed everything.", themePack: "classic", visibility: "PUBLIC", itemIds: [iid("kai",13),iid("kai",14),iid("kai",15),iid("kai",16)] },
  ],
};

export const SEED_CHARACTERS_PART4: SeedCharacter[] = [
  rumple,
  waltonJJr,
  erik,
  solomonKing,
  kaiSterling,
];
